### ISSUE TITLE
Feature Request: add Changelog

### ISSUE THREAD

**Issue by shifoc** [4cq2/googleplay#11]
Add changelog of apps to doc command

**Comment by 4cq2** [comment]
please provide example app

**Comment by shifoc** [comment]
com.whatsapp

**Comment by 4cq2** [comment]
do you mean "What's new"?

https://play.google.com/store/apps/details?id=com.whatsapp

**Comment by shifoc** [comment]
> do you mean "What's new"?
> 
> https://play.google.com/store/apps/details?id=com.whatsapp

Yes

**Comment by 4cq2** [comment]
OK from a `/fdfe/details` response, its under this path:

~~~
1 payload
2 detailsResponse
4 docV2
13 details
1 appDetails
15 recentChangesHtml
~~~

however I dont have an interest in this data, so I would only add a method in response to a donation. If you are interested in that, let me know. Otherwise good luck.

**Comment by shifoc** [comment]
thanks
